#!/usr/bin/env bash
# Run clang-tidy static analysis over odin C/C++ sources using
# ./tool/clang/bin/clang-tidy. Compile flags come from
# $BUILD_DIR/compile_commands.json, regenerated by gn at the start of
# every run. Checks are configured in odin/.clang-tidy.
#
# Usage:
#   ./tidy_odin.sh                       # uses out/
#   BUILD_DIR=out/linux ./tidy_odin.sh   # CI / cross builds

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")" && pwd)"
GN="$REPO_ROOT/tool/gn"
CLANG_TIDY="$REPO_ROOT/tool/clang/bin/clang-tidy"
ODIN_DIR="$REPO_ROOT/odin"
BUILD_DIR="${BUILD_DIR:-$REPO_ROOT/out}"

if [ ! -x "$GN" ]; then
    echo "error: $GN not found or not executable" >&2
    echo "       run ./sync_tools.sh first" >&2
    exit 1
fi

if [ ! -x "$CLANG_TIDY" ]; then
    echo "error: $CLANG_TIDY not found or not executable" >&2
    echo "       run ./sync_tools.sh first" >&2
    exit 1
fi

if [ ! -d "$ODIN_DIR" ]; then
    echo "error: $ODIN_DIR not found" >&2
    exit 1
fi

# Regenerate compile_commands.json so it tracks current GN args / sources.
# gn gen is incremental and idempotent; safe to run on every invocation.
echo "regenerating $BUILD_DIR/compile_commands.json"
"$GN" gen "$BUILD_DIR" --add-export-compile-commands="//odin/*" >/dev/null

HEADER_FILTER="odin/.*"

STATUS=0
COUNT=0
while IFS= read -r -d '' f; do
    rel="${f#$REPO_ROOT/}"
    echo "tidying $rel"
    if ! "$CLANG_TIDY" -p "$BUILD_DIR" --header-filter="$HEADER_FILTER" "$f"; then
        STATUS=1
    fi
    COUNT=$((COUNT + 1))
done < <(find "$ODIN_DIR" \
    -type f \
    \( -name '*.c' -o -name '*.cc' -o -name '*.cpp' \) \
    -print0)

if [ "$COUNT" -eq 0 ]; then
    echo "no C/C++ translation units found under $ODIN_DIR"
    exit 0
fi

if [ "$STATUS" -eq 0 ]; then
    echo "done. tidied $COUNT translation unit(s), no issues."
else
    echo "done. tidied $COUNT translation unit(s), issues found." >&2
fi
exit $STATUS
